name: Update
'on':
  schedule:
  - cron: '* * * * Sun'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update-types:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Update submodules
      run: |-
        git pull --recurse-submodules
        git submodule update --remote --recursive type-generator/lemmy-js-client
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r type-generator/requirements.txt
    - name: Build new types
      run: cd type-generator && python main.py
    - id: date
      name: Get current date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%s')"
    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: update-types/feature/update-types-${{ steps.date.outputs.date }}
        title: Update types from source
